language: objective-c
osx_image: xcode10.2
env: 
  - SCHEME=AppAuth_iOS DESTINATION="'platform=iOS Simulator,name=iPhone 6,OS=8.1'" SDK=iphonesimulator12.2
  - SCHEME=AppAuth_iOS DESTINATION="'platform=iOS Simulator,name=iPhone 6,OS=9.0'" SDK=iphonesimulator12.2
  - SCHEME=AppAuth_iOS DESTINATION="'platform=iOS Simulator,name=iPhone 6,OS=10.0'" SDK=iphonesimulator12.2
  - SCHEME=AppAuth_iOS DESTINATION="'platform=iOS Simulator,name=iPhone 6,OS=11.1'" SDK=iphonesimulator12.2
  - SCHEME=AppAuth-iOS DESTINATION="'platform=iOS Simulator,name=iPhone 6,OS=12.0'" SDK=iphonesimulator12.2
before_script:
  - sudo gem install rubocop cocoapods xcpretty
script:
  - rubocop
  - pod spec lint --allow-warnings
  - eval "set -o pipefail && xcodebuild -project AppAuth.xcodeproj -scheme $SCHEME -sdk $SDK -destination $DESTINATION -enableCodeCoverage YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES OTHERCFLAGS='-Werror' test | xcpretty"
after_success:
  - bash <(curl -s https://codecov.io/bash)

