# frozen_string_literal: true

target 'Example-macOS' do
  platform :osx, '10.10'

  # AppAuth Pod
  # In production, just use `pod 'AppAuth'` without the path reference.
  pod 'AppAuth-logout', path: '../../'
end
