# frozen_string_literal: true

target 'Example-iOS_ObjC' do
  platform :ios, '9.0'

  # AppAuth Pod
  # In production, just use `pod 'AppAuth'` without the path reference.
  pod 'AppAuth-logout', path: '../../'
end
